languageCode = "en"
languageName = "English"
weight = 2
title = "Witchcraft's space"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2006 January 2"
  logo = "img/blowfish_logo_transparent.png"
  description = "A powerful, lightweight theme for Hugo."

[author]
  name = "Witchcraft"
  image = "/img/author2.png"
  headline = "Pale blue dot"
  bio = "All that we see or seem, is but a dream within a dream."
  links = [
    { email = "dszlym666@gmail.com" },
  ]